app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  api:
    github: https://api.github.com
    stack-overflow: https://api.stackexchange.com
    bot: http://localhost:8090

spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres

springdoc:
  swagger-ui:
    path: /

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
