app:
  scheduler:
    enable: true
    interval: 10s
    link-expiration: 10m
  api:
    github: https://api.github.com
    stack-overflow: https://api.stackexchange.com
    bot: http://localhost:8090
  database-access-type: jpa
  retry:
    max-attempts: 3
    type: linear
    delay:
      fixed:
        interval-duration: 1s
      linear:
        initial-interval-duration: 1s
        max-interval-duration: 5s
      exponential:
        initial-interval-duration: 1s
        max-interval-duration: 100s

spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: false

springdoc:
  swagger-ui:
    path: /

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
